### ISSUE TITLE
Water use m2 flowbysector yielding multiple NAICS levels despite target_sector_level is NAICS_6

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#29]
includes for instance 2211 and 1125

applies to https://github.com/USEPA/flowsa/blob/master/flowsa/data/flowbysectormethods/Water_national_2010_m2.yaml
and
https://github.com/USEPA/flowsa/blob/master/flowsa/data/flowbysectormethods/Water_national_2015_m2.yaml

**Comment by WesIngwersen** [comment]
one solution could be to just map it to NAICS_4, which would be sufficient for the currently planned end-use

**Comment by WesIngwersen** [comment]
on hold until #30  is resolved

**Comment by catherinebirney** [comment]
Returning multiple levels of NAICS is done on purpose. Right now, we don't have a method to map thermo and aquaculture to the 6 digit level, so it stops at 4 digits. The code is set up to return NAICS 6 data if it exists, but if it does not, to return the most disaggregated level that exists. There are also some NAICS 5 because employment data doesn't always map to NAICS 6.

**Comment by WesIngwersen** [comment]
@catherinebirney I proposed ti change this method to have target sector length to be Naics_4

**Comment by catherinebirney** [comment]
@WesIngwersen Will do. This change is also necessary for m1.

**Comment by WesIngwersen** [comment]
OK for the current usage but we'll need to get to 6 for a next method.

**Comment by WesIngwersen** [comment]
Decided to generate 6 digit for water use m1 and m2 using simple arbitrary allocation for the couple sectors, thermoelectric and aquaculture, where we lack data
