### ISSUE TITLE
_fuel_MECS allocation not working for stationary combustion CO2 coal

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#322]
Change in in these lines
https://github.com/USEPA/flowsa/blob/82405bcecfbb84f46d954c217c053b7b82569ecf/flowsa/methods/flowbysectormethods/GHG_national_m1.yaml#L381

Running the 2016 m1 with just this method results in error

```
  File "C:/Users/wesle/flowsa/flowsa/flowbysector.py", line 307, in main
    fbs = dataset_allocation_method(
  File "C:\Users\wesle\flowsa\flowsa\fbs_allocation.py", line 144, in dataset_allocation_method
    allocation_helper(fba_allocation_subset, attr, method, v,
  File "C:\Users\wesle\flowsa\flowsa\fbs_allocation.py", line 500, in allocation_helper
    sector_aggregation(modified_fba_allocation)
  File "C:\Users\wesle\flowsa\flowsa\flowbyfunctions.py", line 238, in sector_aggregation
    sector_like_activities = check_activities_sector_like(df_load)
  File "C:\Users\wesle\flowsa\flowsa\common.py", line 350, in check_activities_sector_like
    s = pd.unique(df_load['SourceName'])[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by WesIngwersen** [comment]
all other attributions are commented out to focus on the stationary combustion CO2 one activity set at a time

**Comment by catherinebirney** [comment]
@WesIngwersen Can you run EIA_MECS_Energy FBA locally and see if it works  - you might have an older version of the MECS FBA where the table numbers are not in the Description column. 

Right now the 2016 GHG FBS uses EIA_MECS_Energy 2014 because of the function to find the [closest_value](https://github.com/USEPA/flowsa/blob/refac_GHG_national_mecsallocationfix/flowsa/data_source_scripts/EPA_GHGI.py#L716). We probably want to drop this function and instead load the EIA MECS Energy year from the FBS config file. @bl-young

**Comment by bl-young** [comment]
> Right now the 2016 GHG FBS uses EIA_MECS_Energy 2014 because of the function to find the [closest_value](https://github.com/USEPA/flowsa/blob/refac_GHG_national_mecsallocationfix/flowsa/data_source_scripts/EPA_GHGI.py#L716). We probably want to drop this function and instead load the EIA MECS Energy year from the FBS config file. @bl-young

Good point.

Yes, @WesIngwersen make sure to remove any old EIA MECS files.

**Comment by WesIngwersen** [comment]
The MECS FBAs I've been using have the table # in the description columns

**Comment by bl-young** [comment]
Taking a look now

**Comment by WesIngwersen** [comment]
> Right now the 2016 GHG FBS uses EIA_MECS_Energy 2014 because of the function to find the [closest_value](https://github.com/USEPA/flowsa/blob/refac_GHG_national_mecsallocationfix/flowsa/data_source_scripts/EPA_GHGI.py#L716). We probably want to drop this function and instead load the EIA MECS Energy year from the FBS config file. @bl-young

Yes, i agree that this should not be the case...we need to get the mecs_year being used and not have it find one

**Comment by bl-young** [comment]
This activity set is not designed to use mecs. It should be using the use table as allocation as this is the non-industrial portion:
https://github.com/USEPA/flowsa/blob/13c18d55ce89b0df969655e9d986540ddec4dd40/flowsa/methods/flowbysectormethods/GHG_national_2016_m1.yaml#L348-L353

The later one is the MECS based allocation:
https://github.com/USEPA/flowsa/blob/13c18d55ce89b0df969655e9d986540ddec4dd40/flowsa/methods/flowbysectormethods/GHG_national_2016_m1.yaml#L366-L371

Only the activity_set names that end in `_manufacturing` use MECS as allocation

**Comment by bl-young** [comment]
@WesIngwersen resolved by https://github.com/USEPA/flowsa/commit/fcb95d3687249130f34d77a91fde97cec38991d8

**Comment by WesIngwersen** [comment]
But that commit reverted to using BEA use allocation for those activities which should represent coal-based combustion in industrual and manufacturing  and the point was to change this to using MECS allocation.

**Comment by bl-young** [comment]
There are two activity sets to handle coal combustion emissions (after the industrial coal emissions get split between manufacturing and non-manufacturing). Only the former can use MECS since it applies to sectors 31-33, while the later cannot because it applies to mining and such:


Activity | Sector | Notes | Table
-- | -- | -- | --
Industrial Other Coal Industrial | 11 | 11, 21, 2212, 23 | EPA_GHGI_T_A_14
Industrial Other Coal Industrial | 21 |   | EPA_GHGI_T_A_14
Industrial Other Coal Industrial | 2212 |   | EPA_GHGI_T_A_14
Industrial Other Coal Industrial | 23 |   | EPA_GHGI_T_A_14
Industrial Other Coal Industrial -   Manufacturing | 31 | 31, 32, 33 | EPA_GHGI_T_A_14
Industrial Other Coal Industrial -   Manufacturing | 32 |   | EPA_GHGI_T_A_14
Industrial Other Coal Industrial -   Manufacturing | 33 |   | EPA_GHGI_T_A_14
