### ISSUE TITLE
FBS != FBA errors in GHG_m1 mecsallocationfix/transportation branches

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#324]
There are a number of balance check issues in my local run of 2016. I confirm i updated my local BEA Make and Use FBAs before the run. All the FBAs for the GHGI tables referred to below were created on 2023 -01-26 so reflect the new GHGI 

petroleum in EPA_GHGI_T_3_22b (1.53% less than FBA)

coal_manufacturing in EPA_GHGI_T_A_9 (4.69% less)
natural_gas_manufacturing in EPA_GHGI_T_A_9 (0.03% less than FBA)

coal_manufacturing in EPA_GHGI_T_3_8 (0.23% more than FBA))
ng_manufacturing in EPA_GHGI_T_3_8  (0.03% less than FBA)
ng_manufacturing in EPA_GHGI_T_3_9 (0.03% less than FBA)

_Originally posted by @WesIngwersen in https://github.com/USEPA/flowsa/issues/321#issuecomment-1435676473_

**Comment by WesIngwersen** [comment]
current code we are working with is in the https://github.com/USEPA/flowsa/tree/refac_GHG_national_transport
branch

**Comment by catherinebirney** [comment]
@WesIngwersen @bl-young 
The new differences between FBA and FBS are because of [096e3ea](https://github.com/USEPA/flowsa/commit/096e3eae6786fdad3c24be1659a6f6baa29880a4). I found that in the proportional-flagged method, if a row of data was not flagged (so for this method, a row of EIA MECS data that did not need to be attributed with BEA data) and if the sector was not in the BEA FBA, the FlowRatio (what we multiply FlowAmount by) was set to 0, when it should have been set to 1. Because all BEA data is at NAICS6, we did not lose any EIA MECS NAICS6 data, but EIA MECS data for NAICS3-5 was dropped. This issue did not come up when we were attributing the MECS data with employment because the employment FBA was mapped to NAICS2-6. 

Dropping the EIA MECS NAICS3 means that the ratios for EIA used to attribute the GHG data with are not used as the basis for the ratio denominators and instead EIA MECS NAICS6 are aggregated to create the denominators. Using all NAICS6 was hiding data discrepancies in the original EIA MECS data, as there are cases where published child NAICS sum to be greater than published parent NAICS (like in the screenshot). So these new FBA != FBS discrepancies are caused by using more of the published EIA MECS data. I can revert my commit so we use only NAICS6 data, which should result in FBA values equaling FBS values - the fact that NAICS3-5 ratios were set to 0 was likely an intentional decision on my part 2 years ago to reconcile FBA published data discrepancies.
 
<img width="579" alt="EIA_MECS_Coal_311_Summation" src="https://user-images.githubusercontent.com/60186515/220506013-21220c6b-75d6-4ac7-94dc-9ac14053914c.PNG">

I did fix an error in the code [6e2bf14](https://github.com/USEPA/flowsa/commit/6e2bf14e70177d74006650d87f96cbadbcf737dd) that caused the 4.69% data loss, so now that FBS is 0.23% more than the FBA because child EIA MECS sum to be greater than published parent EIA MECS NAICS3.

Full validation is attached
[GHG_national_2016_m1_v1.3.1_4aec4e2_validation.log](https://github.com/USEPA/flowsa/files/10799541/GHG_national_2016_m1_v1.3.1_4aec4e2_validation.log)

**Comment by bl-young** [comment]
To make sure I'm understanding with the example you give, with the current setup, collectively 3112* sectors would get 19/47 of the total fuel use (40.4%), while 3113* would get 29/47 (61.7%), which adds to greater than 100%. But across all sectors this tends to cancel out so we end up with +/- 0.5% it seems.

And you are saying you can change this so that the calculation here would instead be based on NAICS6, or effectively set the denominator to 48 in this case? Yes I think that would make sense - it seems more important to get to 100% as an allocation source than to use the exact correct reported values at the 3-digit level.

**Comment by catherinebirney** [comment]
Yes - that is the issue with the example i gave

Yes - instead of using published NAICS3, we will sum the published/estimated NAICS6 to create a new denominator (48). And I agree, I think calculating a new denominator is the way to go.

**Comment by WesIngwersen** [comment]
Agree with new denominator - thanks @catherinebirney great problem-solving analysis

**Comment by catherinebirney** [comment]
Ok pushed the changes - results are back to FBS = FBA with one exception - EPA_GHGI_T_5_17 land_area is 0.000158% more than FBA. That table does not use MECS, it uses CoA cropland. I think the issue is similar to the MECS issue in that the denominator is less than published child NAICS because published ag land (naics 11) and ag land, cropland, harvested (naics 111) do not include data for vegetables, woody crops, berries. We already have a function for this issue - so I will test if calling on the function addresses the allocation issue. 

Validation log is attached. 
[GHG_national_2016_m1_v1.3.1_9e2a1c7_validation.log](https://github.com/USEPA/flowsa/files/10804506/GHG_national_2016_m1_v1.3.1_9e2a1c7_validation.log)

**Comment by WesIngwersen** [comment]
> Ok pushed the changes - results are back to FBS = FBA with one exception - EPA_GHGI_T_5_17 land_area is 0.000158% more than FBA. That table does not use MECS, it uses CoA cropland. I think the issue is similar to the MECS issue in that the denominator is less than published child NAICS because published ag land (naics 11) and ag land, cropland, harvested (naics 111) do not include data for vegetables, woody crops, berries. We already have a function for this issue - so I will test if calling on the function addresses the allocation issue.
> 
> Validation log is attached. [GHG_national_2016_m1_v1.3.1_9e2a1c7_validation.log](https://github.com/USEPA/flowsa/files/10804506/GHG_national_2016_m1_v1.3.1_9e2a1c7_validation.log)

Thanks! Certainly that margin of error is acceptable, but in general i agree its good practice to apply that proportional method the same way across different sources
